language: java
jdk:
  - openjdk8

# Travis CI를 어느 브랜치가 푸시될 때 수행할지 지정
# 아래 옵션은 오직 master 브랜치에서 push될 때만 수행
branches:
  only:
    - master

# Travis CI 서버의 Home
# 그레이들을 통해 의존성을 받으면 해당 디렉토리에 캐시해서 같은 의존성은 다음 배포 때 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시되면 수행하는 명령어
script: "./gradlew clean build"
  before_install:
    - chomod +x gradlew

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - pshan0120@gmail.com
